# Github Actions Tutorials:
#
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
# https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners

name: Verify on Push

on:
  push:
    branches: [ master ]
    paths:
      - 'rxmicro-*/**'
  pull_request:
    types: [assigned, opened, edited, reopened]
    paths:
      - 'rxmicro-*/**'

jobs:

  #
  # ------------- Verify on Linux -------------
  #

  run-unit-tests-on-linux:
    name: Run Unit Tests on JDK-${{ matrix.jdk }}/${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # JDK LTS and latest JDK
        jdk: ['11', '14']
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - name: Checkout rxmicro repo
        uses: actions/checkout@v2

      - name: Setup m2 local repo
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: rxmicro-maven-${{ runner.os }}-cache

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Run all tests
        run: mvn --fail-at-end test

  #
  # ------------- Verify Code Quality -------------
  #

  verify-code-quality-using-spotbugs:
    name: Verify Code Quality Using Spotbugs Tool
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rxmicro repo
        uses: actions/checkout@v2

      - name: Setup m2 local repo
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: rxmicro-maven-${{ runner.os }}-cache

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Verify
        run: mvn --fail-at-end -DskipTests -P spotbugs verify

  verify-code-quality-using-pmd:
    name: Verify Code Quality Using PMD Tool
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rxmicro repo
        uses: actions/checkout@v2

      - name: Setup m2 local repo
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: rxmicro-maven-${{ runner.os }}-cache

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Verify
        run: mvn --fail-at-end -DskipTests -P pmd verify
