#
# Copyright (c) 2020. https://rxmicro.io
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Github Actions Tutorials:
#
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://help.github.com/en/actions/reference/events-that-trigger-workflows
#
# https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
# https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners

name: Verify and Publish on Release

# Global settings
env:
  DEFAULT_JDK_LTS_VERSION: '11'
  LAST_JDK_VERSION: '15'
  GRAAL_VM_VERSION: '20.3.0'

on:
  release:
    types: [created]

jobs:
  # -----------------------------------------------------------------------------------------------------
  # ------------- Install the latest version of the RxMicro framework to m2 local cache -----------------
  # -----------------------------------------------------------------------------------------------------
  prepare-examples-verification:
    name: Prepare to verify examples
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout/blob/main/README.md
      - name: Checkout rxmicro repo
        uses: actions/checkout@v2

      # https://github.com/actions/cache/blob/main/README.md
      - name: Setup m2 local repo
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: rxmicro-m2-local-${{ runner.os }}-repo

      # https://github.com/actions/setup-java/blob/main/README.md
      - name: Setup JDK ${{ env.DEFAULT_JDK_LTS_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.DEFAULT_JDK_LTS_VERSION }}

      - name: Prepare
        run: mvn -DskipTests install

      # https://github.com/actions/upload-artifact/blob/main/README.md
      - name: Save latest rxmicro artefacts
        uses: actions/upload-artifact@v2
        with:
          name: rxmicro-framework
          path: ~/.m2/repository/io/rxmicro/
          if-no-files-found: error
          retention-days: 1

      # m2 local repo must not contain the snapshot versions!
      - name: Remove latest rxmicro artefacts
        run: rm -rf ~/.m2/repository/io/rxmicro/
  # -----------------------------------------------------------------------------------------------------
  # ------------- Update User Guide (User Guide must use the latest RxMicro framework version) ----------
  # -----------------------------------------------------------------------------------------------------
  update-user-guide:
    name: Update User Guide
    runs-on: ubuntu-latest
    needs: prepare-examples-verification

    steps:
      # https://github.com/actions/cache/blob/main/README.md
      - name: Setup Maven Local Repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: rxmicro-doc-m2-local-${{ runner.os }}-repo

      # https://github.com/actions/setup-java/blob/main/README.md
      - name: Setup JDK ${{ env.DEFAULT_JDK_LTS_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.DEFAULT_JDK_LTS_VERSION }}

      - name: Checkout 'rxmicro-usage' Repository
        run: git clone https://github.com/rxmicro/rxmicro-usage

      # https://github.com/actions/download-artifact/blob/main/README.md
      - name: Download latest rxmicro artifacts
        uses: actions/download-artifact@v2
        with:
          name: rxmicro-framework
          path: ~/.m2/repository/io/rxmicro/

      - name: Resolve RxMicro Framework Version
        run: find ~/.m2/repository/io/rxmicro/rxmicro/ -maxdepth 1 -type d -name "*-SNAPSHOT" -printf "%f\n" > RXMICRO_VERSION.txt

      - name: Recompile Examples of REST-based microservice documentations
        run: |
          LATEST_VERSION=$(cat RXMICRO_VERSION.txt)
          cd rxmicro-usage/examples/group-documentation-asciidoctor
          mvn -DskipTests -Drxmicro.version=$LATEST_VERSION -B compile --file documentation-asciidoctor-custom-sections/pom.xml
          mvn -DskipTests -Drxmicro.version=$LATEST_VERSION -B compile --file documentation-asciidoctor-echo/pom.xml
          mvn -DskipTests -Drxmicro.version=$LATEST_VERSION -B compile --file documentation-asciidoctor-errors/pom.xml
          mvn -DskipTests -Drxmicro.version=$LATEST_VERSION -B compile --file documentation-asciidoctor-quick-start/pom.xml
          mvn -DskipTests -Drxmicro.version=$LATEST_VERSION -B compile --file documentation-asciidoctor-validation/pom.xml
          mvn -DskipTests -Drxmicro.version=$LATEST_VERSION -B compile --file documentation-asciidoctor-metadata-annotations/pom.xml
          mvn -DskipTests -Drxmicro.version=$LATEST_VERSION -B compile --file documentation-asciidoctor-metadata-pomxml/pom.xml

      - name: Build the Last Version of RxMicro User Guide
        run: |
          LATEST_VERSION=$(cat RXMICRO_VERSION.txt)
          RELEASE_VERSION=$(echo $LATEST_VERSION | sed 's/-SNAPSHOT//g')
          cd rxmicro-usage/documentation/
          mvn -Drxmicro.version=$RELEASE_VERSION -B verify --file pom.xml

      - name: Clone the `docs` Repository
        run: git clone https://github.com/rxmicro/docs

      - name: Update the `docs` Repository
        run: |
          rm -R docs/latest/
          mkdir docs/latest/
          mv -v rxmicro-usage/documentation/target/generated-docs/images docs/latest
          mv -v rxmicro-usage/documentation/target/generated-docs/project-documentation-examples docs/latest
          mv -v rxmicro-usage/documentation/target/generated-docs/user-guide docs/latest
          mv -v rxmicro-usage/documentation/target/generated-docs/user-guide.html docs/latest
          mv -v rxmicro-usage/documentation/target/generated-docs/user-guide.pdf docs/latest
          mkdir docs/latest/styles/
          mv -v rxmicro-usage/documentation/target/generated-docs/styles/rxmicro-doc.min.css docs/latest/styles/

      # https://github.com/actions/upload-artifact/blob/main/README.md
      - name: Save latest documentation
        uses: actions/upload-artifact@v2
        with:
          name: rxmicro-documentaion
          path: docs
          if-no-files-found: error
          retention-days: 1
  # -----------------------------------------------------------------------------------------------------
  # ------------- Publish to Maven Central --------------------------------------------------------------
  # -----------------------------------------------------------------------------------------------------
  publish-to-maven-central:
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    needs:
      - update-user-guide

    steps:
      # https://github.com/actions/checkout/blob/main/README.md
      - name: Checkout rxmicro repo
        uses: actions/checkout@v2

      # https://github.com/actions/cache/blob/main/README.md
      - name: Setup m2 local repo
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: rxmicro-m2-local-${{ runner.os }}-repo

      # https://github.com/actions/setup-java/blob/main/README.md
      - name: Setup JDK ${{ env.DEFAULT_JDK_LTS_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.DEFAULT_JDK_LTS_VERSION }}

      - name: Prepare deploy
        run: |
          cp .mvn/settings.xml ~/.m2/settings.xml
          sed -i 's/OSSRH_PASSWORD/${{ secrets.OSSRH_PASSWORD}}/' ~/.m2/settings.xml
          sed -i 's/OSSRH_PASSPHRASE/${{ secrets.OSSRH_PASSPHRASE}}/' ~/.m2/settings.xml
          echo '${{secrets.SIGN_KEY}}' > rxmicro.txt
          gpg --quiet --batch --yes --passphrase="${{ secrets.OSSRH_PASSPHRASE}}" --allow-secret-key-import --import rxmicro.txt

      - name: Update version of the RxMicro framework
        run: |
          LATEST_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          RELEASE_VERSION=$(echo $LATEST_VERSION | sed 's/-SNAPSHOT//g')
          mvn versions:set -DnewVersion=$RELEASE_VERSION

      - name: Deploy to OSSRH
        run: mvn -P release -DskipTests deploy

      - name: Resolve release tag
        id: resolve-release-tag
        run: |
          LATEST_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          RELEASE_VERSION=$(echo $LATEST_VERSION | sed 's/-SNAPSHOT//g')
          echo "::set-output name=version::$RELEASE_VERSION"

      # https://github.com/ncipollo/release-action/blob/main/README.md
      - name: Update github release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.resolve-release-tag.outputs.version }}
          prerelease: false
          allowUpdates: true
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
  # -----------------------------------------------------------------------------------------------------
  # ------------- Upload the latest version of User Guide -----------------------------------------------
  # -----------------------------------------------------------------------------------------------------
  upload-user-guide:
    name: Upload User Guide
    runs-on: ubuntu-latest
    needs: publish-to-maven-central

    steps:
      - name: Clone the `docs` Repository
        run: |
          git clone https://github.com/rxmicro/docs
          rm -R docs

      # https://github.com/actions/download-artifact/blob/main/README.md
      - name: Download latest rxmicro documentation
        uses: actions/download-artifact@v2
        with:
          name: rxmicro-documentaion
          path: docs

      # Print dir tree with file size for debug purposes
      - name: Show downloaded rxmicro documentation
        run: |
          sudo apt install tree
          tree -hD docs

      - name: Commit and Push Changes to the `docs` Repository
        run: |
          cd docs
          git config user.email "rxmicro.io@gmail.com"
          git config user.name "rxmicro"
          git add --all
          git commit --amend -m "Update user guide. Commit#${{ github.sha }}"
          git remote set-url origin https://rxmicro:${{ secrets.AUTO_UPDATE_RX_MICRO_IO_DOC_ACCESS_TOKEN }}@github.com/rxmicro/docs.git
          git push --force origin master
