#
# Copyright (c) 2020. https://rxmicro.io
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Github Actions Tutorials:
#
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://help.github.com/en/actions/reference/events-that-trigger-workflows
#
# https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
# https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners

name: Verify on Push

on:
  push:
    branches: [ master ]
    paths:
      - 'rxmicro-*/src/main/java/**'
      - 'rxmicro-*/src/test/java/**'
  pull_request:
    types: [assigned, opened, edited, reopened]
    paths:
      - 'rxmicro-*/src/main/java/**'
      - 'rxmicro-*/src/test/java/**'

jobs:

  #
  # ------------- Run Unit tests on Linux with JDK LTS and JDK latest version -------------
  #

  test-on-linux:
    name: Test on JDK-${{ matrix.jdk }}/${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # JDK LTS and latest JDK
        jdk: ['11', '14']
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - name: Checkout rxmicro repo
        uses: actions/checkout@v2

      - name: Setup m2 local repo
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: rxmicro-maven-${{ runner.os }}-cache

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Run all tests
        run: mvn --fail-at-end test

  #
  # ------------- Verify Code Quality via Spotbugs Tool -------------
  # ------------------ https://spotbugs.github.io/ ------------------
  #

  verify-via-spotbugs:
    name: Verify via Spotbugs Tool
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rxmicro repo
        uses: actions/checkout@v2

      - name: Setup m2 local repo
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: rxmicro-maven-${{ runner.os }}-cache

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Verify
        run: mvn --fail-at-end -DskipTests -P spotbugs verify

  #
  # ------------- Verify Code Quality via PMD Tool -------------
  # ------------------ https://pmd.github.io/ ------------------
  #

  verify-via-pmd:
    name: Verify via PMD Tool
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rxmicro repo
        uses: actions/checkout@v2

      - name: Setup m2 local repo
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: rxmicro-maven-${{ runner.os }}-cache

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Verify
        run: mvn --fail-at-end -DskipTests -P pmd verify

  #
  # ------------- Verify Code Quality via Checkstyle Tool -------------
  # --------------- https://checkstyle.sourceforge.io/ ----------------
  #

  verify-via-checkstyle:
    name: Verify via Checkstyle Tool
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rxmicro repo
        uses: actions/checkout@v2

      - name: Setup m2 local repo
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: rxmicro-maven-${{ runner.os }}-cache

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Verify
        run: mvn --fail-at-end -DskipTests -P checkstyle verify
